apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  minReadySeconds: 10
  selector:
    matchLabels:
      app: nginx
  Strategy:
    type: RollingUpdate
    rollingUpdate: 0
    maxsurge: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      serviceAccountName: nginx
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
          name: http-web-svc
        resources:
          requests: 
            memory: 1 Gi
            cpu: 500m
          limits:
            memory: 2 Gi
            cpu: 1
        
